config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: "static_pages#root"
  
  resources :users, only: [:new, :create]
  resource :session, only: [:new, :create, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/campaign.rb
class Campaign < ApplicationRecord

    validates :name, presence: true
    validates :goal, presence: true

    has_many :donations,
        primary_key: :id,
        foreign_key: :campaign_id,
        class_name: :Donation

    has_many :matches,
        primary_key: :id,
        foreign_key: :campaign_id,
        class_name: :Match
end

app/models/donation.rb
class Donation < ApplicationRecord

    validates :amount, presence: true
    
    belongs_to :campaign,
        primary_key: :id,
        foreign_key: :campaign_id,
        class_name: :Campaign
end

app/models/match.rb
class Match < ApplicationRecord

    belongs_to :campaign,
        primary_key: :id,
        foreign_key: :campaign_id,
        class_name: :Campaign
end

app/models/user.rb
class User < ApplicationRecord

    validates :username, presence: true, uniqueness: true
    validates :password_digest, presence: true
    validates :session_token, presence: true
    validates :password, length: {minimum: 6, allow_nil: true}

    after_initialize :ensure_session_token
    attr_reader :password

    def self.find_by_credentials(username, password) 
        user = User.find_by(username: username)
        user && user.is_password?(password) ? user : nil
    end

    def self.generate_session_token
        SecureRandom::urlsafe_base64(16)
    end

    def reset_session_token!
        self.session_token = self.class.generate_session_token
        self.save!
        self.session_token
    end

    def is_password?(password) 
        bcryptPassword = BCrypt::Password.new(self.password_digest)
        bcryptPassword.is_password?(password)
    end

    def password=(password) 
        @password = password
        self.password_digest = BCrypt::Password.create(password)
    end

    private
    def ensure_session_token
        self.session_token ||= self.class.generate_session_token
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    helper_method :current_user, :logged_in?

    def current_user
        @user ||= User.find_by(session_token: session[:session_token])
    end

    def login(user) 
        session_token = user.reset_session_token!
        session[:session_token] = session_token
    end

    def logged_in?
        !!current_user
    end

    def logout
        current_user.reset_session_token!
        session[:session_token] = nil
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

    def new
        render :new
    end

    def create
        @user = User.find_by_credentials(
            params[:user][:username],
            params[:user][:password]
        )

        if @user
            login(@user)
            redirect_to root_url
        else
            flash.now[:errors] = ["Username/Password didn't match"]
            render :new
            # render json: ["Username/Password didn't match"], status: :unprocessable_entity
        end
    end

    def destroy
        self.logout
        redirect_to new_session_url
    end

    private
    def user_params
        params.require(:user).permit(:username, :password)
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

    def root
        @user = current_user
        render :root
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

    def new
        render :new
    end

    def create
        @newUser = User.new(user_params)
    
        if @newUser.save
            login(@newUser)
            redirect_to root_url
        else
            flash.now[:errors] = @newUser.errors.full_messages
            render :new
        end
    end

    private
    def user_params
        params.require(:user).permit(:username, :password)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_controller_helper.rb
module SessionsControllerHelper
end

app/helpers/users_controller_helper.rb
module UsersControllerHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Project1</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>

    <% if flash.now[:errors]%>
      <ul>
        <% flash.now[:errors].each do |error|%>
            <li><%= error %></li>
        <% end%>
      </ul>
    <% end%>

    <% if logged_in? %>
      <form action="<%= session_url %>" method="post">
        <input type="hidden" name="_method" value="delete">
        <input type="hidden" name="authenticity_token" value=<%= form_authenticity_token %>>
        <input type="submit" value="logout">
      </form>
    <% end%>
  </body>
</html>

app/views/static_pages/root.html.erb
<% if current_user %>
<h1>Welcome <%=  @user.username %></h1>
<% end %>

<h1>Practice Rails </h1>

<% if !current_user%>
    <a href="<%= new_session_url %>">Login</a>
    <a href="<%= new_user_url %>">SignUp</a>
<% end%>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<form action="<%= users_url %>" method="post">
    <input type="hidden" name="authenticity_token" value=<%= form_authenticity_token %>>
    <label for="username">Username:</label>
    <input type="text" name="user[username]" id="username">
    <label for="password">Password:</label>
    <input type="password" name="user[password]" id="password">

    <input type="submit" value="Sign Up">
</form>
<a href="<%= root_url %>">Back to home</a>

app/views/users/show.html.erb
<h1>Hello <%= @user.username %></h1>